-- CreateEnum
CREATE TYPE "DokumentKategorie" AS ENUM ('ANSCHAFFUNGSKOSTEN', 'BETRIEBS_NEBENKOSTEN', 'FINANZIERUNG_KREDITE_VERSICHERUNGEN', 'INDIVIDUELLE_KOSTEN', 'MIETE_NEBENKOSTEN_KAUTION', 'RENOVIERUNG_REPARATUR_INVESTITIONEN', 'SONSTIGE_AUSGABEN', 'SONSTIGE_EINNAHMEN');

-- AlterTable
ALTER TABLE "Dokument" ADD COLUMN     "kategorie" "DokumentKategorie";
